changelog:
  categories:
    - title: "Breaking Changes 🛠"
      labels:
        - "breaking change"
    - title: "Exciting New Features 🎉"
      labels:
        - "enhancement"
    - title: "Dependency Updates"
      labels:
        - "renovate"
    - title: "Other Changes"
      labels:
        - "*"
