name: test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # https://nodejs.org/en/about/releases/
        node-version: ['18', '20']
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        test-script: npm test
